FROM ubuntu:22.04
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update -y && apt-get install -y apt-utils jq vim curl sudo
ARG DOCKER_VER=19.03.8
RUN curl -fsSLO https://download.docker.com/linux/static/stable/aarch64/docker-${DOCKER_VER}.tgz \
  && tar xzvf docker-${DOCKER_VER}.tgz --strip 1 -C /usr/bin docker/docker \
  && rm docker-${DOCKER_VER}.tgz

RUN curl -sL https://deb.nodesource.com/setup_20.x  | bash -
RUN apt-get -y install nodejs
RUN npm install -g npm
RUN npm install -g hzn-cli

WORKDIR /oh
COPY . /oh

#RUN npm install
#RUN chmod 777 /oh/node_modules/content-type/HISTORY.md
RUN npm run build

EXPOSE 8888

RUN ["chmod", "+x", "/oh/input.sh"]
RUN ["chmod", "+x", "/oh/agent-install.sh"]

ENTRYPOINT ["sh", "/oh/input.sh"]
